version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: '09:00'
      timezone: Asia/Seoul
    open-pull-requests-limit: 3
    groups:
      javascript:
        patterns: ['*']
    labels: [dependencies, javascript]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: '10:00'
      timezone: Asia/Seoul
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns: ['*']
    labels: [dependencies, github-actions]
